---
title: "<NuxtErrorBoundary>"
description: <NuxtErrorBoundary> 组件处理其默认插槽中发生的客户端错误。
links:
  - label: 源码
    icon: i-simple-icons-github
    to: https://github.com/nuxt/nuxt/blob/main/packages/nuxt/src/app/components/nuxt-error-boundary.vue
    size: xs
---

::tip
`<NuxtErrorBoundary>` 在内部使用了 Vue 的 [`onErrorCaptured`](https://vue.zhcndoc.com/api/composition-api-lifecycle.html#onerrorcaptured) 钩子。
::

## 事件

- `@error`：当组件的默认插槽抛出错误时触发的事件。

  ```vue
  <template>
    <NuxtErrorBoundary @error="logSomeError">
      <!-- ... -->
    </NuxtErrorBoundary>
  </template>
  ```

## 插槽

- `#error`：指定错误时显示的备用内容。

  ```vue
    <template>
      <NuxtErrorBoundary>
        <!-- ... -->
        <template #error="{ error, clearError }">
          <p>发生了一个错误: {{ error }}</p>

          <button @click="clearError">清除错误</button>
        </template>
      </NuxtErrorBoundary>
    </template>
  ```

:read-more{to="/docs/getting-started/error-handling"}

## 示例

### 在脚本中访问 `error` 和 `clearError`

你可以在组件的脚本中如下访问 `error` 和 `clearError` 属性：

```vue
<template>
  <NuxtErrorBoundary ref="errorBoundary">
    <!-- ... -->
  </NuxtErrorBoundary>
</template>

<script setup lang="ts">
const errorBoundary = useTemplateRef('errorBoundary')

// errorBoundary.value?.error
// errorBoundary.value?.clearError()
</script>
```
